trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - src/*
      - test/*
      - azure-pipelines.yml

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
- name: buildConfiguration
  value: "Release"
- name: dotNetFramework
  value: 'net6.0'
- name: dotNetVersion
  value: '6.0.x'
- name: targetRuntime
  value: 'linux-x64'

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: simplic/build-infrastructure
      endpoint: simplic-bot
      
steps:
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  - script: dotnet restore src/simplic-oxs.sln
    displayName: 'Restore solution'

  - script: dotnet build src/simplic-oxs.sln --configuration $(buldConfiguration)
    displayName: 'Build solution'


  - script: dotnet pack src/simplic-oxs.sln
    displayName: 'Create nuget packages'